on:
  workflow_dispatch:
    inputs:
      titleText:
        description: "Text for the video"
        required: true
        default: "Yakut başlıyor..."
      fileName:
        description: "Name of the video file"
        required: true
        default: "YakutIntro.mp4"
name: Render video
jobs:
  render:
    name: Render video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: npm i
      - run: npm run build ${{github.event.inputs.fileName}} -- --props="$WORKFLOW_INPUT"
        env:
          WORKFLOW_INPUT: ${{ toJson(github.event.inputs) }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{github.event.inputs.fileName}}
          path: ${{github.event.inputs.fileName}}
